import 'package:flutter/material.dart';

enum SkillNodeState {
  locked,      // Gri / Kilitli
  unlocked,    // Beyaz (2s Hold / 1 Rep / Başlangıç)
  inProgress,  // Pembe (6s Hold / 3 Reps)
  mastered,    // Yeşil (12s+ Hold / 6+ Reps)
}

class VisualSkillNode {
  final String id;
  final String name;
  final String branch;
  final Offset position;
  final List<String> childrenIds;
  SkillNodeState state;
  final String description;

  VisualSkillNode({
    required this.id,
    required this.name,
    required this.branch,
    required this.position,
    this.childrenIds = const [],
    this.state = SkillNodeState.locked,
    required this.description,
  });
}

class CalisthenicsVisualTreeData {
  static List<VisualSkillNode> getNodes() {
    return [
      // ==========================================
      // 🌟 1. CORE (MERKEZ BÖLGE) - MERKEZ ÇEKİRDEK
      // ==========================================
      VisualSkillNode(
        id: 'core_root',
        name: 'Hollow Body',
        branch: 'CORE',
        position: const Offset(750, 700),
        childrenIds: ['core_plank', 'h_push_root', 'v_push_root', 'h_pull_root', 'v_pull_root', 'legs_root', 'rope_root'],
        state: SkillNodeState.unlocked, // Ana kök düğüm
        description: 'Temel merkez bölge gerilimi (15s+ Hold).',
      ),
      VisualSkillNode(
        id: 'core_plank',
        name: 'Plank Hold',
        branch: 'CORE',
        position: const Offset(750, 630),
        childrenIds: ['core_leg_raise', 'core_l_sit', 'core_dragon_flag'],
        state: SkillNodeState.locked,
        description: 'Düz merkez stabilizasyonu (60s+ Hold).',
      ),
      VisualSkillNode(
        id: 'core_leg_raise',
        name: 'Hanging Leg Raise',
        branch: 'CORE',
        position: const Offset(750, 560),
        childrenIds: ['core_toes_to_bar'],
        state: SkillNodeState.locked,
        description: 'Barda asılı bacakları 90 derece kaldırma.',
      ),
      VisualSkillNode(
        id: 'core_toes_to_bar',
        name: 'Toes To Bar',
        branch: 'CORE',
        position: const Offset(750, 490),
        state: SkillNodeState.locked,
        description: 'Barda bacakları yukarı fırlatıp bara ayak değdirme.',
      ),
      VisualSkillNode(
        id: 'core_l_sit',
        name: 'Floor L-Sit',
        branch: 'CORE',
        position: const Offset(690, 560),
        childrenIds: ['core_v_sit'],
        state: SkillNodeState.locked,
        description: 'Yerde bacaklar 90 derece düz L duruşu.',
      ),
      VisualSkillNode(
        id: 'core_v_sit',
        name: 'V-Sit Hold',
        branch: 'CORE',
        position: const Offset(670, 480),
        childrenIds: ['core_manna'],
        state: SkillNodeState.locked,
        description: 'Gövde ve bacaklar 45 derece havada V oturuşu.',
      ),
      VisualSkillNode(
        id: 'core_manna',
        name: 'Manna',
        branch: 'CORE',
        position: const Offset(650, 400),
        state: SkillNodeState.locked,
        description: 'Zirve: Bacaklar başın gerisinde havada asılı duruş.',
      ),
      VisualSkillNode(
        id: 'core_dragon_flag',
        name: 'Dragon Flag',
        branch: 'CORE',
        position: const Offset(810, 560),
        childrenIds: ['core_human_flag'],
        state: SkillNodeState.locked,
        description: 'Bruce Lee efsanevi düz vücut bayrağı.',
      ),
      VisualSkillNode(
        id: 'core_human_flag',
        name: 'Human Flag',
        branch: 'CORE',
        position: const Offset(840, 470),
        state: SkillNodeState.locked,
        description: 'Dikey direkte tam yatay insan bayrağı.',
      ),

      // ==========================================
      // 🪢 2. JUMP ROPE (İP ATLAMA & FREESTYLE) - YUKARI DAL
      // ==========================================
      VisualSkillNode(
        id: 'rope_root',
        name: 'Basic Bounce',
        branch: 'JUMP ROPE',
        position: const Offset(750, 420),
        childrenIds: ['rope_boxer_step', 'rope_side_swing'],
        state: SkillNodeState.unlocked, // Başlangıç ip atlama açık
        description: 'Temel çift ayak zıplama (Kesintisiz 100 tekrar ritim).',
      ),
      VisualSkillNode(
        id: 'rope_boxer_step',
        name: 'Boxer Step',
        branch: 'JUMP ROPE',
        position: const Offset(700, 350),
        childrenIds: ['rope_high_knees', 'rope_double_under'],
        state: SkillNodeState.locked,
        description: 'Boksör Adımı: Ayak değiştirerek hafif ve akıcı sıçrama.',
      ),
      VisualSkillNode(
        id: 'rope_side_swing',
        name: 'Side Swing',
        branch: 'JUMP ROPE',
        position: const Offset(800, 350),
        childrenIds: ['rope_criss_cross', 'rope_side_cross'],
        state: SkillNodeState.locked,
        description: 'Yan Savurma: İpi vücudun sağ ve solundan savurarak ritim tutma.',
      ),
      VisualSkillNode(
        id: 'rope_high_knees',
        name: 'High Knee Sprint',
        branch: 'JUMP ROPE',
        position: const Offset(640, 280),
        state: SkillNodeState.locked,
        description: 'Diz Çekerek Hızlı İp Atlama (60 saniye yüksek tempo).',
      ),
      VisualSkillNode(
        id: 'rope_criss_cross',
        name: 'Criss-Cross',
        branch: 'JUMP ROPE',
        position: const Offset(750, 280),
        childrenIds: ['rope_side_cross'],
        state: SkillNodeState.locked,
        description: 'Çapraz Atlama: Kolları göğüs önünde çaprazlayarak ipin içinden geçiş.',
      ),
      VisualSkillNode(
        id: 'rope_double_under',
        name: 'Double Under (DU)',
        branch: 'JUMP ROPE',
        position: const Offset(700, 210),
        childrenIds: ['rope_triple_under', 'rope_cross_double'],
        state: SkillNodeState.locked,
        description: 'Çift Tur: Tek sıçrayışta ipi altından iki kez geçirme (25+ tekrar).',
      ),
      VisualSkillNode(
        id: 'rope_side_cross',
        name: 'Side Swing Cross',
        branch: 'JUMP ROPE',
        position: const Offset(800, 210),
        childrenIds: ['rope_mic_release'],
        state: SkillNodeState.locked,
        description: 'Yan savurmadan anında çapraz atlamaya akıcı freestyle geçiş.',
      ),
      VisualSkillNode(
        id: 'rope_triple_under',
        name: 'Triple Under (TU)',
        branch: 'JUMP ROPE',
        position: const Offset(660, 140),
        childrenIds: ['rope_quad_under'],
        state: SkillNodeState.locked,
        description: 'Üçlü Tur: Tek zıplayışta ipi havada üç tam tur döndürme.',
      ),
      VisualSkillNode(
        id: 'rope_cross_double',
        name: 'Cross Double Under',
        branch: 'JUMP ROPE',
        position: const Offset(750, 140),
        state: SkillNodeState.locked,
        description: 'Southpaw: Çift tur dönerken kollar çapraz pozisyonda kalır.',
      ),
      VisualSkillNode(
        id: 'rope_mic_release',
        name: 'Mic Release & Catch',
        branch: 'JUMP ROPE',
        position: const Offset(840, 140),
        state: SkillNodeState.locked,
        description: 'Freestyle Numarası: İp sapını havaya fırlatıp diğer elle yakalama.',
      ),
      VisualSkillNode(
        id: 'rope_quad_under',
        name: 'Quad Under Sprint',
        branch: 'JUMP ROPE',
        position: const Offset(750, 70),
        state: SkillNodeState.locked,
        description: 'Zirve: Tek sıçrayışta 4 tur döndürme / 130+ RPM hız sürati.',
      ),

      // ==========================================
      // 🛡️ 3. HORIZONTAL PUSH (YATAY İTİŞ & PLANCHE) - SOL ALT DAL
      // ==========================================
      VisualSkillNode(
        id: 'h_push_root',
        name: 'Knee Push-up',
        branch: 'HORIZONTAL PUSH',
        position: const Offset(640, 730),
        childrenIds: ['h_push_reg'],
        state: SkillNodeState.unlocked,
        description: 'Dizler üzerinde temel şınav.',
      ),
      VisualSkillNode(
        id: 'h_push_reg',
        name: 'Regular Push-up',
        branch: 'HORIZONTAL PUSH',
        position: const Offset(550, 760),
        childrenIds: ['h_push_decline', 'h_push_diamond', 'h_push_wide'],
        state: SkillNodeState.locked,
        description: '3x20 nizami şınav.',
      ),
      VisualSkillNode(
        id: 'h_push_decline',
        name: 'Decline Push-up',
        branch: 'HORIZONTAL PUSH',
        position: const Offset(570, 850),
        childrenIds: ['h_push_clap'],
        state: SkillNodeState.locked,
        description: 'Ayaklar sehpa üzerinde yüksekte üst göğüs şınavı.',
      ),
      VisualSkillNode(
        id: 'h_push_diamond',
        name: 'Diamond Push-up',
        branch: 'HORIZONTAL PUSH',
        position: const Offset(470, 720),
        childrenIds: ['h_push_pseudo'],
        state: SkillNodeState.locked,
        description: 'Elmas şeklinde bitişik ellerle triceps şınavı.',
      ),
      VisualSkillNode(
        id: 'h_push_wide',
        name: 'Archer Push-up',
        branch: 'HORIZONTAL PUSH',
        position: const Offset(480, 830),
        childrenIds: ['h_push_one_arm'],
        state: SkillNodeState.locked,
        description: 'Tek kola ağırlık vererek okçu şınavı.',
      ),
      VisualSkillNode(
        id: 'h_push_clap',
        name: 'Clap Push-up',
        branch: 'HORIZONTAL PUSH',
        position: const Offset(400, 860),
        childrenIds: ['h_push_superman'],
        state: SkillNodeState.locked,
        description: 'Patlayıcı itiş ile havada elleri birbirine vurma.',
      ),
      VisualSkillNode(
        id: 'h_push_pseudo',
        name: 'Pseudo Planche Push-up',
        branch: 'HORIZONTAL PUSH',
        position: const Offset(380, 690),
        childrenIds: ['h_push_tuck_planche'],
        state: SkillNodeState.locked,
        description: 'Öne eğik, omuzları ileri basarak planche şınavı.',
      ),
      VisualSkillNode(
        id: 'h_push_one_arm',
        name: 'One Arm Push-up',
        branch: 'HORIZONTAL PUSH',
        position: const Offset(330, 880),
        state: SkillNodeState.locked,
        description: 'Tek kol üzerinde nizami şınav.',
      ),
      VisualSkillNode(
        id: 'h_push_superman',
        name: 'Superman Push-up',
        branch: 'HORIZONTAL PUSH',
        position: const Offset(260, 900),
        state: SkillNodeState.locked,
        description: 'Tüm vücut havaya fırlayıp kollar öne uzatılır.',
      ),
      VisualSkillNode(
        id: 'h_push_tuck_planche',
        name: 'Tuck Planche',
        branch: 'HORIZONTAL PUSH',
        position: const Offset(290, 660),
        childrenIds: ['h_push_adv_tuck_planche'],
        state: SkillNodeState.locked,
        description: 'Dizler karında havada planche duruşu.',
      ),
      VisualSkillNode(
        id: 'h_push_adv_tuck_planche',
        name: 'Adv. Tuck Planche',
        branch: 'HORIZONTAL PUSH',
        position: const Offset(210, 640),
        childrenIds: ['h_push_straddle_planche'],
        state: SkillNodeState.locked,
        description: 'Sırt düz, bacaklar 90 derece bükülü planche.',
      ),
      VisualSkillNode(
        id: 'h_push_straddle_planche',
        name: 'Straddle Planche',
        branch: 'HORIZONTAL PUSH',
        position: const Offset(140, 610),
        childrenIds: ['h_push_full_planche'],
        state: SkillNodeState.locked,
        description: 'Bacaklar açık yere paralel planche duruşu.',
      ),
      VisualSkillNode(
        id: 'h_push_full_planche',
        name: 'Full Planche',
        branch: 'HORIZONTAL PUSH',
        position: const Offset(80, 560),
        childrenIds: ['h_push_planche_pushup'],
        state: SkillNodeState.locked,
        description: 'Zirve: Düz tahta gibi havada tam Planche (10s+ Hold).',
      ),
      VisualSkillNode(
        id: 'h_push_planche_pushup',
        name: 'Planche Push-up',
        branch: 'HORIZONTAL PUSH',
        position: const Offset(40, 480),
        state: SkillNodeState.locked,
        description: 'Full Planche pozisyonunda havada şınav tekrarı.',
      ),

      // ==========================================
      // 🏹 4. VERTICAL PUSH (DİKEY İTİŞ & AMUT) - SOL ÜST DAL
      // ==========================================
      VisualSkillNode(
        id: 'v_push_root',
        name: 'Bench Dips',
        branch: 'VERTICAL PUSH',
        position: const Offset(660, 640),
        childrenIds: ['v_push_dips'],
        state: SkillNodeState.unlocked,
        description: 'Sehpa üzerinde temel dips.',
      ),
      VisualSkillNode(
        id: 'v_push_dips',
        name: 'Parallel Bar Dips',
        branch: 'VERTICAL PUSH',
        position: const Offset(580, 560),
        childrenIds: ['v_push_pike', 'v_push_straight_bar', 'v_push_ring_dips'],
        state: SkillNodeState.locked,
        description: 'Paralel barda tam derinlik dips.',
      ),
      VisualSkillNode(
        id: 'v_push_pike',
        name: 'Pike Push-up',
        branch: 'VERTICAL PUSH',
        position: const Offset(500, 500),
        childrenIds: ['v_push_crow_pose', 'v_push_wall_hs'],
        state: SkillNodeState.locked,
        description: 'Pike duruşunda dikey omuz şınavı.',
      ),
      VisualSkillNode(
        id: 'v_push_straight_bar',
        name: 'Straight Bar Dips',
        branch: 'VERTICAL PUSH',
        position: const Offset(540, 430),
        childrenIds: ['v_push_korean_dips'],
        state: SkillNodeState.locked,
        description: 'Düz tek barda gövdeyi öne yatırarak dips.',
      ),
      VisualSkillNode(
        id: 'v_push_ring_dips',
        name: 'Ring Dips',
        branch: 'VERTICAL PUSH',
        position: const Offset(460, 420),
        childrenIds: ['v_push_ring_hs'],
        state: SkillNodeState.locked,
        description: 'Jimnastik halkalarında titremesiz serbest dips.',
      ),
      VisualSkillNode(
        id: 'v_push_korean_dips',
        name: 'Korean Dips',
        branch: 'VERTICAL PUSH',
        position: const Offset(490, 350),
        state: SkillNodeState.locked,
        description: 'Bar vücudun arkasındayken dips.',
      ),
      VisualSkillNode(
        id: 'v_push_crow_pose',
        name: 'Crow Pose',
        branch: 'VERTICAL PUSH',
        position: const Offset(430, 520),
        childrenIds: ['v_push_hs_walk'],
        state: SkillNodeState.locked,
        description: 'Dizler dirseklerin üzerinde karga duruşu dengesi.',
      ),
      VisualSkillNode(
        id: 'v_push_wall_hs',
        name: 'Wall Handstand Push-up',
        branch: 'VERTICAL PUSH',
        position: const Offset(370, 460),
        childrenIds: ['v_push_free_hs', 'v_push_hs_walk'],
        state: SkillNodeState.locked,
        description: 'Duvarda nizami amut şınavı.',
      ),
      VisualSkillNode(
        id: 'v_push_hs_walk',
        name: 'Handstand Walk',
        branch: 'VERTICAL PUSH',
        position: const Offset(310, 410),
        childrenIds: ['v_push_free_hs'],
        state: SkillNodeState.locked,
        description: 'Amut pozisyonunda eller üzerinde 10 metre yürüme.',
      ),
      VisualSkillNode(
        id: 'v_push_free_hs',
        name: 'Freestanding HSPU',
        branch: 'VERTICAL PUSH',
        position: const Offset(250, 360),
        childrenIds: ['v_push_90deg_pushup'],
        state: SkillNodeState.locked,
        description: 'Duvarsız, boşlukta amutta tam şınav.',
      ),
      VisualSkillNode(
        id: 'v_push_ring_hs',
        name: 'Ring Handstand',
        branch: 'VERTICAL PUSH',
        position: const Offset(200, 310),
        state: SkillNodeState.locked,
        description: 'Serbest sallanan halkalarda amutta sabit kalış.',
      ),
      VisualSkillNode(
        id: 'v_push_90deg_pushup',
        name: '90° Push-up (Hollowback)',
        branch: 'VERTICAL PUSH',
        position: const Offset(150, 250),
        childrenIds: ['v_push_one_arm_hs'],
        state: SkillNodeState.locked,
        description: 'Amuttan yatay plancheye inip tekrar amuda basış.',
      ),
      VisualSkillNode(
        id: 'v_push_one_arm_hs',
        name: 'One Arm Handstand',
        branch: 'VERTICAL PUSH',
        position: const Offset(90, 180),
        state: SkillNodeState.locked,
        description: 'Zirve: Tek el üzerinde amutta kusursuz denge (5s+ Hold).',
      ),

      // ==========================================
      // 🦅 5. VERTICAL PULL (DİKEY ÇEKİŞ & MUSCLE-UP) - SAĞ ÜST DAL
      // ==========================================
      VisualSkillNode(
        id: 'v_pull_root',
        name: 'Dead Hang (60s)',
        branch: 'VERTICAL PULL',
        position: const Offset(840, 640),
        childrenIds: ['v_pull_scapular', 'v_pull_pullup'],
        state: SkillNodeState.unlocked,
        description: 'Barda 60 saniye asılı kalma ve çelik tutuş gücü.',
      ),
      VisualSkillNode(
        id: 'v_pull_scapular',
        name: 'Scapular Pull-up',
        branch: 'VERTICAL PULL',
        position: const Offset(890, 580),
        childrenIds: ['v_pull_pullup'],
        state: SkillNodeState.locked,
        description: 'Kolları bükmeden kürek kemiklerini sıkıştırıp çekiş.',
      ),
      VisualSkillNode(
        id: 'v_pull_pullup',
        name: 'Regular Pull-up',
        branch: 'VERTICAL PULL',
        position: const Offset(940, 530),
        childrenIds: ['v_pull_wide', 'v_pull_l_sit', 'v_pull_chest_to_bar'],
        state: SkillNodeState.locked,
        description: '3x10 nizami çene bar üstü barfiks.',
      ),
      VisualSkillNode(
        id: 'v_pull_wide',
        name: 'Wide Grip Pull-up',
        branch: 'VERTICAL PULL',
        position: const Offset(990, 610),
        childrenIds: ['v_pull_clap'],
        state: SkillNodeState.locked,
        description: 'Geniş tutuşla kanatları maksimum açan barfiks.',
      ),
      VisualSkillNode(
        id: 'v_pull_l_sit',
        name: 'L-Sit Pull-up',
        branch: 'VERTICAL PULL',
        position: const Offset(1020, 490),
        childrenIds: ['v_pull_high_pullup'],
        state: SkillNodeState.locked,
        description: 'Bacaklar 90 derece L açısındayken barfiks çekişi.',
      ),
      VisualSkillNode(
        id: 'v_pull_chest_to_bar',
        name: 'Chest To Bar',
        branch: 'VERTICAL PULL',
        position: const Offset(1060, 560),
        childrenIds: ['v_pull_archer'],
        state: SkillNodeState.locked,
        description: 'Göğsü bara sertçe değdiren patlayıcı çekiş.',
      ),
      VisualSkillNode(
        id: 'v_pull_clap',
        name: 'Clap Pull-up',
        branch: 'VERTICAL PULL',
        position: const Offset(1100, 630),
        state: SkillNodeState.locked,
        description: 'Barfiks tepe noktasında barı bırakıp el çırpma.',
      ),
      VisualSkillNode(
        id: 'v_pull_high_pullup',
        name: 'High Pull-up (Karına)',
        branch: 'VERTICAL PULL',
        position: const Offset(1090, 450),
        childrenIds: ['v_pull_muscle_up'],
        state: SkillNodeState.locked,
        description: 'Barı göbek deliğine kadar çeken patlayıcı güç.',
      ),
      VisualSkillNode(
        id: 'v_pull_archer',
        name: 'Archer Pull-up',
        branch: 'VERTICAL PULL',
        position: const Offset(1150, 540),
        childrenIds: ['v_pull_one_arm'],
        state: SkillNodeState.locked,
        description: 'Bir kol yana düz açılırken diğer kolla barfiks.',
      ),
      VisualSkillNode(
        id: 'v_pull_muscle_up',
        name: 'Bar Muscle-up',
        branch: 'VERTICAL PULL',
        position: const Offset(1170, 420),
        childrenIds: ['v_pull_strict_muscle_up', 'v_pull_ring_muscle_up'],
        state: SkillNodeState.locked,
        description: 'Çekip barın üzerine patlayıcı şekilde geçiş.',
      ),
      VisualSkillNode(
        id: 'v_pull_strict_muscle_up',
        name: 'Strict Muscle-up',
        branch: 'VERTICAL PULL',
        position: const Offset(1230, 370),
        childrenIds: ['v_pull_360_muscle_up', 'v_pull_one_arm'],
        state: SkillNodeState.locked,
        description: 'Savurmasız, yavaş ve nizami kas gücü muscle-up.',
      ),
      VisualSkillNode(
        id: 'v_pull_ring_muscle_up',
        name: 'Ring Muscle-up',
        branch: 'VERTICAL PULL',
        position: const Offset(1290, 420),
        state: SkillNodeState.locked,
        description: 'Jimnastik halkalarında nizami ve derin muscle-up.',
      ),
      VisualSkillNode(
        id: 'v_pull_360_muscle_up',
        name: '360 Spin Muscle-up',
        branch: 'VERTICAL PULL',
        position: const Offset(1250, 290),
        state: SkillNodeState.locked,
        description: 'Freestyle: Bardan atlayıp havada 360 derece dönüp yakalama.',
      ),
      VisualSkillNode(
        id: 'v_pull_one_arm',
        name: 'One Arm Pull-up (OAP)',
        branch: 'VERTICAL PULL',
        position: const Offset(1330, 250),
        state: SkillNodeState.locked,
        description: 'Zirve: Tek kol ile nizami barfiks çekişi.',
      ),

      // ==========================================
      // ⛓️ 6. HORIZONTAL PULL (YATAY ÇEKİŞ & LEVER) - SAĞ ALT DAL
      // ==========================================
      VisualSkillNode(
        id: 'h_pull_root',
        name: 'Inverted Row',
        branch: 'HORIZONTAL PULL',
        position: const Offset(840, 730),
        childrenIds: ['h_pull_ring_row', 'h_pull_tuck_fl'],
        state: SkillNodeState.unlocked,
        description: 'Yatay avustralya barfiksi çekişi.',
      ),
      VisualSkillNode(
        id: 'h_pull_ring_row',
        name: 'Ring Inverted Row',
        branch: 'HORIZONTAL PULL',
        position: const Offset(920, 780),
        childrenIds: ['h_pull_archer_row'],
        state: SkillNodeState.locked,
        description: 'Jimnastik halkasında serbest açılı yatay çekiş.',
      ),
      VisualSkillNode(
        id: 'h_pull_archer_row',
        name: 'Archer Row',
        branch: 'HORIZONTAL PULL',
        position: const Offset(990, 850),
        state: SkillNodeState.locked,
        description: 'Tek kol yana uzanırken diğer kolla çekiş.',
      ),
      VisualSkillNode(
        id: 'h_pull_tuck_fl',
        name: 'Tuck Front Lever',
        branch: 'HORIZONTAL PULL',
        position: const Offset(960, 710),
        childrenIds: ['h_pull_adv_tuck', 'h_pull_skin_the_cat'],
        state: SkillNodeState.locked,
        description: 'Dizler karında havada yatay asılı kalma.',
      ),
      VisualSkillNode(
        id: 'h_pull_adv_tuck',
        name: 'Adv. Tuck Front Lever',
        branch: 'HORIZONTAL PULL',
        position: const Offset(1040, 740),
        childrenIds: ['h_pull_straddle_fl'],
        state: SkillNodeState.locked,
        description: 'Sırt düz, bacaklar 90 derece bükülü lever.',
      ),
      VisualSkillNode(
        id: 'h_pull_skin_the_cat',
        name: 'Skin The Cat',
        branch: 'HORIZONTAL PULL',
        position: const Offset(1020, 840),
        childrenIds: ['h_pull_back_lever'],
        state: SkillNodeState.locked,
        description: 'Kollar arasından geriye dönerek omuz mobilizasyonu.',
      ),
      VisualSkillNode(
        id: 'h_pull_back_lever',
        name: 'Full Back Lever',
        branch: 'HORIZONTAL PULL',
        position: const Offset(1080, 890),
        state: SkillNodeState.locked,
        description: 'Gözler yere bakar pozisyonda tam düz sırt duruşu.',
      ),
      VisualSkillNode(
        id: 'h_pull_straddle_fl',
        name: 'Straddle Front Lever',
        branch: 'HORIZONTAL PULL',
        position: const Offset(1120, 760),
        childrenIds: ['h_pull_full_fl'],
        state: SkillNodeState.locked,
        description: 'Bacaklar iki yana açık yatay Front Lever.',
      ),
      VisualSkillNode(
        id: 'h_pull_full_fl',
        name: 'Full Front Lever',
        branch: 'HORIZONTAL PULL',
        position: const Offset(1190, 790),
        childrenIds: ['h_pull_fl_touch', 'h_pull_victorian'],
        state: SkillNodeState.locked,
        description: 'Yere paralel düz tahta gibi havada asılı kalış (10s+).',
      ),
      VisualSkillNode(
        id: 'h_pull_fl_touch',
        name: 'Front Lever Row / Touch',
        branch: 'HORIZONTAL PULL',
        position: const Offset(1250, 830),
        state: SkillNodeState.locked,
        description: 'Tam Front Lever pozisyonunda barı karna çekiş.',
      ),
      VisualSkillNode(
        id: 'h_pull_victorian',
        name: 'Victorian Cross',
        branch: 'HORIZONTAL PULL',
        position: const Offset(1310, 890),
        state: SkillNodeState.locked,
        description: 'Zirve: Kollar geride paralel barda vücudu yatay tutuş.',
      ),

      // ==========================================
      // 🦵 7. LEGS (BACAK & PATLAYICILIK) - AŞAĞI DAL
      // ==========================================
      VisualSkillNode(
        id: 'legs_root',
        name: 'Bodyweight Squat',
        branch: 'LEGS',
        position: const Offset(750, 790),
        childrenIds: ['legs_jump_squat', 'legs_bulgarian', 'legs_cossack'],
        state: SkillNodeState.unlocked,
        description: '50 nizami derin vücut ağırlığı squat.',
      ),
      VisualSkillNode(
        id: 'legs_jump_squat',
        name: 'Jump Squat',
        branch: 'LEGS',
        position: const Offset(690, 860),
        childrenIds: ['legs_sissy', 'legs_box_jump'],
        state: SkillNodeState.locked,
        description: 'Derin çömelip havaya patlayıcı dikey sıçrama.',
      ),
      VisualSkillNode(
        id: 'legs_bulgarian',
        name: 'Bulgarian Split Squat',
        branch: 'LEGS',
        position: const Offset(810, 860),
        childrenIds: ['legs_nordic'],
        state: SkillNodeState.locked,
        description: 'Arka ayak yüksekte tek bacak kalça ve quadriceps yüklenmesi.',
      ),
      VisualSkillNode(
        id: 'legs_cossack',
        name: 'Cossack Squat',
        branch: 'LEGS',
        position: const Offset(750, 920),
        childrenIds: ['legs_pistol'],
        state: SkillNodeState.locked,
        description: 'Yanlara derin ve esnek tek bacak çöküşü.',
      ),
      VisualSkillNode(
        id: 'legs_sissy',
        name: 'Sissy Squat',
        branch: 'LEGS',
        position: const Offset(670, 990),
        childrenIds: ['legs_shrimp'],
        state: SkillNodeState.locked,
        description: 'Dizler öne bükülüp gövde geriye yatarak izole quadriceps.',
      ),
      VisualSkillNode(
        id: 'legs_pistol',
        name: 'Pistol Squat',
        branch: 'LEGS',
        position: const Offset(750, 1000),
        childrenIds: ['legs_dragon_pistol'],
        state: SkillNodeState.locked,
        description: 'Tek bacak tam derinlik tabanca squat (10+ tekrar).',
      ),
      VisualSkillNode(
        id: 'legs_nordic',
        name: 'Nordic Hamstring Curl',
        branch: 'LEGS',
        position: const Offset(830, 990),
        state: SkillNodeState.locked,
        description: 'Dizler üzerinde vücut ağırlığıyla arka bacak izolasyonu.',
      ),
      VisualSkillNode(
        id: 'legs_shrimp',
        name: 'Shrimp Squat',
        branch: 'LEGS',
        position: const Offset(690, 1070),
        state: SkillNodeState.locked,
        description: 'Arka bacak elle tutulu vaziyette tek bacak çöküş.',
      ),
      VisualSkillNode(
        id: 'legs_dragon_pistol',
        name: 'Dragon Pistol Squat',
        branch: 'LEGS',
        position: const Offset(750, 1090),
        state: SkillNodeState.locked,
        description: 'Arkadan bacağı yana çapraz uzatarak yapılan akrobatik squat.',
      ),
      VisualSkillNode(
        id: 'legs_box_jump',
        name: 'High Box Jump (100cm+)',
        branch: 'LEGS',
        position: const Offset(820, 1140),
        state: SkillNodeState.locked,
        description: 'Zirve: 1 metrelik yüksek kutuya patlayıcı sıçrama.',
      ),
    ];
  }
}
